CREATE DATABASE MOBCARE;

USE MOBCARE;

CREATE TABLE IF NOT EXISTS `MOBCARE`.`TAXONOMIA` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `NOME` VARCHAR(45) NOT NULL,
  `DESCRICAO` VARCHAR(255) NULL,
  `DATA_CRIACAO` DATETIME NULL,
  `DATA_ALTERACAO` DATETIME NULL,
  `ATIVO` TINYINT(1) NOT NULL DEFAULT 1,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB;

CREATE TABLE IF NOT EXISTS `MOBCARE`.`DOMINIO` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `NOME` VARCHAR(100) NOT NULL,
  `DESCRICAO` VARCHAR(255) NULL,
  `ID_TAXONOMIA` INT NOT NULL,
  `DATA_CRIACAO` DATETIME NULL,
  `DATA_ALTERACAO` DATETIME NULL,
  `ATIVO` TINYINT(1) NOT NULL DEFAULT 1,
  PRIMARY KEY (`ID`),
  INDEX `ID_TAXONOMIA_idx` (`ID_TAXONOMIA` ASC),
  CONSTRAINT `ID_TAXONOMIA`
    FOREIGN KEY (`ID_TAXONOMIA`)
    REFERENCES `MOBCARE`.`TAXONOMIA` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE TABLE IF NOT EXISTS `MOBCARE`.`CLASSE` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `ID_DOMINIO` INT NOT NULL,
  `NOME` VARCHAR(100) NULL,
  `DESCRICAO` VARCHAR(255) NULL,
  `DATA_CRIACAO` DATETIME NULL,
  `DATA_ALTERACAO` DATETIME NULL,
  `ATIVO` TINYINT(1) NOT NULL DEFAULT 1,
  PRIMARY KEY (`ID`),
  INDEX `ID_DOMINIO_idx` (`ID_DOMINIO` ASC),
  CONSTRAINT `ID_DOMINIO`
    FOREIGN KEY (`ID_DOMINIO`)
    REFERENCES `MOBCARE`.`DOMINIO` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE TABLE IF NOT EXISTS `MOBCARE`.`DIAGNOSTICO` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `ID_CLASSE` INT NOT NULL,
  `CODIGO` VARCHAR(20) NULL,
  `DESCRICAO` VARCHAR(255) NULL,
  `DATA_CRIACAO` DATETIME NULL,
  `DATA_ALTERACAO` DATETIME NULL,
  `ATIVO` TINYINT(1) NOT NULL DEFAULT 1,
  PRIMARY KEY (`ID`),
  INDEX `ID_CLASSE_idx` (`ID_CLASSE` ASC),
  CONSTRAINT `ID_CLASSE`
    FOREIGN KEY (`ID_CLASSE`)
    REFERENCES `MOBCARE`.`CLASSE` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE OR REPLACE VIEW `classe_view` AS
    SELECT 
        `c`.`ID` AS `ID`,
        `c`.`ID_DOMINIO` AS `ID_DOMINIO`,
        `c`.`NOME` AS `NOME`,
        `c`.`DESCRICAO` AS `DESCRICAO`,
        `c`.`DATA_CRIACAO` AS `DATA_CRIACAO`,
        `c`.`DATA_ALTERACAO` AS `DATA_ALTERACAO`,
        `c`.`ATIVO` AS `ATIVO`,
        `d`.`NOME` AS `DOMINIO`,
        `d`.`DESCRICAO` AS `DOMINIO_DESCRICAO`,
        `t`.`NOME` AS `TAXONOMIA`
    FROM
        ((`classe` `c`
        JOIN `dominio` `d` ON ((`c`.`ID_DOMINIO` = `d`.`ID`)))
        JOIN `taxonomia` `t` ON ((`d`.`ID_TAXONOMIA` = `t`.`ID`)))
    WHERE
        (`c`.`ATIVO` = 1);
		
CREATE OR REPLACE VIEW `diagnostico_view` AS
    SELECT 
        `d`.`ID` AS `ID`,
        `d`.`ID_CLASSE` AS `ID_CLASSE`,
        `d`.`CODIGO` AS `CODIGO`,
        `d`.`DESCRICAO` AS `DESCRICAO`,
        `d`.`DATA_CRIACAO` AS `DATA_CRIACAO`,
        `d`.`DATA_ALTERACAO` AS `DATA_ALTERACAO`,
        `d`.`ATIVO` AS `ATIVO`,
        `c`.`NOME` AS `CLASSE`,
        `c`.`DESCRICAO` AS `CLASSE_DESCRICAO`,
        `dom`.`NOME` AS `DOMINIO`,
        `dom`.`DESCRICAO` AS `DOMINIO_DESCRICAO`,
        `t`.`NOME` AS `TAXONOMIA`
    FROM
        (((`diagnostico` `d`
        JOIN `classe` `c` ON ((`d`.`ID_CLASSE` = `c`.`ID`)))
        JOIN `dominio` `dom` ON ((`c`.`ID_DOMINIO` = `dom`.`ID`)))
        JOIN `taxonomia` `t` ON ((`dom`.`ID_TAXONOMIA` = `t`.`ID`)))
    WHERE
        (`d`.`ATIVO` = 1);
		
CREATE OR REPLACE VIEW `dominio_view` AS
    SELECT 
        `d`.`ID` AS `ID`,
        `d`.`NOME` AS `NOME`,
        `d`.`DESCRICAO` AS `DESCRICAO`,
        `d`.`ID_TAXONOMIA` AS `ID_TAXONOMIA`,
        `d`.`DATA_CRIACAO` AS `DATA_CRIACAO`,
        `d`.`DATA_ALTERACAO` AS `DATA_ALTERACAO`,
        `d`.`ATIVO` AS `ATIVO`,
        `t`.`NOME` AS `TAXONOMIA`,
        `t`.`DESCRICAO` AS `TAXONOMIA_DESCRICAO`
    FROM
        (`dominio` `d`
        JOIN `taxonomia` `t` ON ((`d`.`ID_TAXONOMIA` = `t`.`ID`)))
        WHERE 
			(`d`.`ATIVO` = 1);